[package]
name = "arp-scan"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
pnet = "0.34.0"
clap = { version = "4.5", features = ["derive"] }
cidr = "0.2"
csv = "1"

[profile.release]
lto = true
codegen-units = 1
opt-level = "z"
strip = true